# Generated by Django 6.0.5 on 2026-05-24 20:25

import apps.chats.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0018_alter_goods_id_alter_goodsimage_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.chats.models.generate_short_uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_message",
                    models.TextField(blank=True, verbose_name="最后一条消息"),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="最后消息时间"
                    ),
                ),
                (
                    "unread_initiator",
                    models.IntegerField(default=0, verbose_name="发起方未读数"),
                ),
                (
                    "unread_receiver",
                    models.IntegerField(default=0, verbose_name="接收方未读数"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "正常"), (1, "屏蔽"), (2, "关闭")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="goods.goods",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天会话",
                "verbose_name_plural": "聊天会话",
                "db_table": "second_hand_chat_session",
                "unique_together": {("goods", "initiator", "receiver")},
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.chats.models.generate_short_uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("system", "系统"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "send_status",
                    models.SmallIntegerField(
                        choices=[(0, "pending"), (1, "sent"), (2, "failed")],
                        default=1,
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息聊天",
                "verbose_name_plural": "消息聊天",
                "db_table": "second_hand_message",
                "ordering": ["created_at"],
            },
        ),
    ]
