# Generated by Django 6.0.1 on 2026-03-06 09:17

import shortuuid.main
import apps.users.models
import apps.users.utils.randomUserNickname
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="邮箱"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="联系电话"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default=apps.users.utils.randomUserNickname.generate_default_nickname,
                        max_length=30,
                        verbose_name="昵称",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="真实姓名"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="身份证号"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "普通用户"), (2, "平台审核员"), (3, "系统管理员")],
                        default=1,
                        verbose_name="系统角色",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="实名认证状态"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="后台登录权限"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="账号是否激活"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "db_table": "second_hand_user",
            },
            managers=[
                ("objects", apps.users.models.PlatformUserManager()),
            ],
        ),
    ]
