# Generated by Django 6.0.1 on 2026-04-11 07:08

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_platformuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformuser",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="default_01.png",
                max_length=100,
                verbose_name="头像",
            ),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="bio",
            field=models.CharField(
                blank=True,
                default="这个人很懒，什么都没写~",
                max_length=200,
                verbose_name="个性签名",
            ),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "保密"), (1, "男"), (2, "女")],
                default=0,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="platformuser",
            name="location",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="所在城市"
            ),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
