# Generated by Django 6.0.1 on 2026-04-11 07:39

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_platformuser_avatar_platformuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformuser",
            name="avatar",
            field=models.CharField(
                blank=True,
                default="avatars/default_01.png",
                max_length=100,
                verbose_name="头像",
            ),
        ),
        migrations.AlterField(
            model_name="platformuser",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
