# Generated by Django 6.0.1 on 2026-04-11 08:31

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_platformuser_avatar_alter_platformuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformuser",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=20, verbose_name="联系人姓名"),
                ),
                ("telephone", models.CharField(max_length=11, verbose_name="手机号")),
                ("province", models.CharField(max_length=50, verbose_name="省")),
                ("city", models.CharField(max_length=50, verbose_name="市")),
                ("district", models.CharField(max_length=50, verbose_name="区/县")),
                (
                    "detail_address",
                    models.CharField(max_length=200, verbose_name="详细地址"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认收货地址"),
                ),
                (
                    "is_default_return",
                    models.BooleanField(
                        default=False, verbose_name="默认退货/发货地址"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_address",
                "ordering": ["-is_default", "-is_default_return", "-updated_at"],
            },
        ),
    ]
