# Generated by Django 6.0.1 on 2026-04-15 10:22

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_platformuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformuser",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
