# Generated by Django 6.0.5 on 2026-05-24 20:25

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_platformuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformuser",
            name="id",
            field=models.CharField(
                default=apps.users.models.generate_short_uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
