# Generated by Django 6.0.1 on 2026-03-10 10:38

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="商品标题")),
                ("description", models.TextField(verbose_name="商品详情")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="售价"
                    ),
                ),
                (
                    "condition",
                    models.IntegerField(
                        choices=[
                            (100, "全新"),
                            (99, "99新"),
                            (95, "95新"),
                            (90, "90新"),
                            (80, "80新及以下"),
                        ],
                        default=95,
                        verbose_name="商品成色",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "草稿"),
                            (1, "在售中"),
                            (2, "已售出"),
                            (3, "已下架"),
                        ],
                        default=1,
                        verbose_name="商品状态",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_goods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "second_hand_goods",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsImage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="goods/images/%Y/%m/", verbose_name="商品图片"
                    ),
                ),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="是否为主图"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="goods.goods",
                    ),
                ),
            ],
            options={
                "db_table": "second_hand_goods_image",
                "ordering": ["-is_cover", "created_at"],
            },
        ),
    ]
