# Generated by Django 6.0.1 on 2026-03-21 13:31

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
                "db_table": "goods_category",
                "ordering": ["sort"],
            },
        ),
        migrations.AlterModelOptions(
            name="goods",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "商品信息",
                "verbose_name_plural": "商品信息",
            },
        ),
        migrations.RemoveField(
            model_name="goods",
            name="condition",
        ),
        migrations.AddField(
            model_name="goods",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="动态属性"
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_goods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="卖家",
            ),
        ),
        migrations.AlterField(
            model_name="goodsimage",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="goods",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goods.category",
                verbose_name="商品分类",
            ),
        ),
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="属性名")),
                (
                    "input_type",
                    models.CharField(
                        choices=[("radio", "单选按钮"), ("select", "下拉框")],
                        default="radio",
                        max_length=20,
                        verbose_name="展现形式",
                    ),
                ),
                ("options", models.JSONField(default=list, verbose_name="备选项")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="goods.category",
                        verbose_name="所属大类",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类动态属性",
                "verbose_name_plural": "分类动态属性",
                "db_table": "goods_category_attribute",
            },
        ),
    ]
