# Generated by Django 6.0.1 on 2026-03-21 16:17

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_category_alter_goods_options_remove_goods_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="delivery_method",
            field=models.IntegerField(
                choices=[(1, "包邮"), (2, "到付"), (3, "自提")],
                default=1,
                verbose_name="发货方式",
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="goodsimage",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
