# Generated by Django 6.0.5 on 2026-05-24 20:25

import apps.goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0017_alter_goods_id_alter_goodsimage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="id",
            field=models.CharField(
                default=apps.goods.models.generate_short_uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="goodsimage",
            name="id",
            field=models.CharField(
                default=apps.goods.models.generate_short_uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
