# Generated by Django 6.0.1 on 2026-04-20 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0017_alter_goods_id_alter_goodsimage_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_sn",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="订单号",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单金额"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待付款"),
                            (1, "待发货"),
                            (2, "已发货"),
                            (3, "交易成功"),
                            (4, "交易取消"),
                            (5, "售后/退款中"),
                        ],
                        default=0,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=20, verbose_name="收货人姓名"),
                ),
                (
                    "receiver_phone",
                    models.CharField(max_length=11, verbose_name="收货人电话"),
                ),
                (
                    "receiver_address",
                    models.CharField(max_length=200, verbose_name="收货详细地址"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="快递单号"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="付款时间"
                    ),
                ),
                (
                    "consign_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发货时间"
                    ),
                ),
                (
                    "finish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="成交时间"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="买家",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="goods.goods",
                        verbose_name="交易商品",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sell_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="卖家",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易订单",
                "verbose_name_plural": "交易订单",
                "db_table": "trade_order",
            },
        ),
    ]
