# Generated by Django 6.0.1 on 2026-04-20 21:58

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_sn",
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default=apps.orders.models.generate_order_id,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="订单号",
            ),
        ),
    ]
