# Generated by Django 6.0.1 on 2026-04-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_order_sn_order_order_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="second_hand_order",
        ),
    ]
