# Generated by Django 6.0.1 on 2026-04-20 23:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_alter_goods_id_alter_goodsimage_id'),
        ('orders', '0003_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods', verbose_name='交易商品'),
        ),
    ]