# Generated by Django 6.0.1 on 2026-04-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="goods_image",
            field=models.CharField(
                default="", max_length=255, verbose_name="商品主图快照"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="goods_title",
            field=models.CharField(
                default="", max_length=100, verbose_name="商品名称快照"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "待付款"),
                    (1, "待发货"),
                    (2, "待收货"),
                    (3, "交易成功"),
                    (4, "交易取消"),
                    (5, "售后/退款中"),
                ],
                default=0,
                verbose_name="订单状态",
            ),
        ),
    ]
