# Generated by Django 6.0.1 on 2026-04-20 23:30

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_goods_image_order_snapshot_image_and_more'),
    ]

    operations = []
