# Generated by Django 6.0.1 on 2026-04-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_goods_image_order_goods_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="goods_image",
            new_name="snapshot_image",
        ),
        migrations.RemoveField(
            model_name="order",
            name="goods_title",
        ),
        migrations.AddField(
            model_name="order",
            name="snapshot_content",
            field=models.TextField(default="", verbose_name="商品文案快照"),
        ),
    ]
